module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]

module.exports.campDescriptions = [
  "Nestled beneath whispering pines, our camp offers true forest serenity. Wake to the scent of pine needles and the melody of birdsong.",
  "Camp beside a shimmering lake where sunsets reflect like watercolor. Spend your days kayaking, your nights under a canopy of stars.",
  "Hidden in a peaceful valley, this retreat reconnects you with the earth. Unplug, slow down, and breathe deeply in nature’s arms.",
  "Where wildflowers bloom and trails wind through ancient trees. Each path invites wonder, each evening ends with firelit stories.",
  "Tucked away in the hills, our campsite offers the perfect escape. Enjoy crisp air, clear skies, and silence you can feel.",
  "Experience mornings wrapped in mist and evenings wrapped in blankets. Campfires crackle as laughter and stars fill the night.",
  "Nestled between riverbanks and tall woods, this camp is a dream. Watch dragonflies skim the water and roast s’mores at twilight.",
  "A place where you wake with the sun and fall asleep to the moon. Nature’s rhythms guide your days and soothe your soul.",
  "Feel the breeze through the trees and the soft earth underfoot. This is where serenity and adventure meet.",
  "Camp by a meadow filled with wild blooms and butterflies. Sip coffee with a view and walk trails kissed by sunlight.",
  "Mountains stand guard while you rest in peaceful wilderness. A perfect spot for sunrise hikes and soul-deep quiet.",
  "A lakeside haven where reflections shimmer and spirits lift. Paddle by day, stargaze by night, and breathe in calm.",
  "Let birds be your morning alarm and fireflies your nightlight. This camp is a gentle pause in life’s busy rhythm.",
  "Retreat to a forest of old-growth trees and mossy paths. Here, everything is slower, softer, more meaningful.",
  "Camp under an endless sky where constellations tell their tales. Every night feels like magic; every morning, a fresh beginning.",
  "Escape the noise and find your quiet beside a still stream. Let water’s song and wind’s whispers be your soundtrack.",
  "Settle into a valley where deer roam and the air is pure. Evenings glow golden and peace comes easily here.",
  "Where the crackle of the fire meets the hush of tall trees. Each moment feels deeper, each breath feels fuller.",
  "A backcountry gem where trails lead to waterfalls and wonder. Return to your tent with tired feet and a happy heart.",
  "Under a sky ablaze with stars, find your spark again. This camp rekindles joy, rest, and connection.",
  "Perched on a quiet hilltop, this site is made for dreaming. Gaze out at forests, clouds, and the far-off horizon.",
  "Where nature writes the story and you become part of it. Camp here and leave with new memories etched in wild places.",
  "Surrounded by whispering oaks and gentle hills. This camp is nature’s lullaby and life’s gentle reminder.",
  "Hammocks swing between pines in perfect rhythm. Come nap, read, and let time slow to a breath.",
  "From sunrise glow to twilight hush, every moment is magic. Let your soul rest in the arms of nature.",
  "Trade city lights for starlight and honks for owl calls. Here, peace is natural, and wonder is daily.",
  "A meadow alive with birds, breeze, and blooming quiet. Camp here to hear yourself think again.",
  "Lush green surrounds you, while a clear stream chats nearby. It's not just camping—it’s healing.",
  "Where the forest floor is your welcome mat and stars your ceiling. Sleep soundly in the heart of the wild.",
  "Breathe the pine-scented air and walk barefoot on earth. This is freedom—raw, grounding, and real.",
  "Where each trail invites curiosity and each night brings comfort. Come explore, then come home to your tent.",
  "Let your campfire warm your hands and your heart. The forest listens, and so should you.",
  "A campsite kissed by sunlight and softened by moss. It’s where nature slows your heartbeat and lifts your spirit.",
  "Tents dot a field touched by the breeze and golden hour light. The sky opens up, and so will you.",
  "Watch the mist roll over hills as you sip your morning tea. This is a stillness we all long for.",
  "The forest doesn’t just surround you—it welcomes you. Settle into this quiet corner of the world.",
  "Where laughter echoes off canyon walls and joy is in every breath. Adventure thrives here, side-by-side with calm.",
  "A perfect blend of solitude and exploration. This camp is a gift you give yourself.",
  "Trade screens for streams and Wi-Fi for wilderness. This is connection in its purest form.",
  "Drift asleep to the sound of crickets and wind through the leaves. No alarms. Just the rhythm of the wild.",
  "Find warmth by the fire and light in the stars. Here, every element brings comfort.",
  "Camp on the edge of a forest and the beginning of discovery. Step outside and into something real.",
  "Where trails lead to nowhere in particular—but everywhere meaningful. Wander freely and come back new.",
  "Each moment here is a gentle reminder: you are part of nature. And nature takes good care of its own.",
  "Morning dew, birdsong, and coffee by the fire. It’s the simple things that feel the most alive here.",
  "Under cedar trees and open skies, peace finds you. And you’ll wonder why you ever left.",
  "Chase fireflies with your kids and share stories by lantern light. Camp becomes the memory you’ll never forget.",
  "Find joy in building a fire, hiking a trail, pitching a tent. Here, small things feel big again.",
  "Camp beside a river that has carved stories into stone. Let it carry your worries away.",
  "From rocky ridges to gentle meadows, this place holds wonder. All you have to do is arrive—and breathe."
];

